export const countries = [
  'Jordan',
  'Northern Mariana Islands',
  'Serbia',
  'Andorra',
  'Turks and Caicos Islands',
  'Bermuda',
  'Antarctica',
  'Bolivia',
  'Libya',
  'Mali',
  'Armenia',
  'Mauritius',
  'Maldives',
  'American Samoa',
  'North Macedonia',
  'Ethiopia',
  'Greenland',
  'Iraq',
  'Guatemala',
  'Trinidad and Tobago',
  'Peru',
  'Suriname',
  'Sweden',
  'New Caledonia',
  'French Polynesia',
  'Benin',
  'Estonia',
  'Falkland Islands',
  'Guam',
  'Zimbabwe',
  'Slovakia',
  'Netherlands',
  'Ecuador',
  'Saudi Arabia',
  'United Arab Emirates',
  'Afghanistan',
  'United States Minor Outlying Islands',
  'Central African Republic',
  'Panama',
  'Vatican City',
  'Syria',
  'Vanuatu',
  'Honduras',
  'Kiribati',
  'Chile',
  'Burkina Faso',
  'Saint Kitts and Nevis',
  'Saint Barthélemy',
  'Mexico',
  'China',
  'Timor-Leste',
  'British Indian Ocean Territory',
  'South Sudan',
  'Eswatini',
  'Uzbekistan',
  'Indonesia',
  'Paraguay',
  'Monaco',
  'Grenada',
  'Croatia',
  'Poland',
  'Bosnia and Herzegovina',
  'Canada',
  'Portugal',
  'Brazil',
  'Mauritania',
  'Israel',
  'Curaçao',
  'Brunei',
  'Angola',
  'Malta',
  'Belarus',
  'Turkey',
  'Finland',
  'Gibraltar',
  'Bhutan',
  'Spain',
  'Venezuela',
  'Qatar',
  'Czechia',
  'Kuwait',
  'Montenegro',
  'Bouvet Island',
  'India',
  'New Zealand',
  'Jamaica',
  'Cayman Islands',
  'San Marino',
  'Republic of the Congo',
  'Pakistan',
  'France',
  'Kazakhstan',
  'Bahrain',
  'Fiji',
  'Iceland',
  'Myanmar',
  'Bangladesh',
  'Philippines',
  'Equatorial Guinea',
  'Ireland',
  'Nepal',
  'Yemen',
  'South Korea',
  'Denmark',
  'Oman',
  'Saint Vincent and the Grenadines',
  'Eritrea',
  'Australia',
  'Iran',
  'El Salvador',
  'Tanzania',
  'Guadeloupe',
  'Solomon Islands',
  'Kenya',
  'Dominican Republic',
  'Greece',
  'Guernsey',
  'Rwanda',
  'Saint Pierre and Miquelon',
  'Tuvalu',
  'Taiwan',
  'Guyana',
  'Seychelles',
  'North Korea',
  'Botswana',
  'Cambodia',
  'Barbados',
  'Colombia',
  'Ukraine',
  'Ivory Coast',
  'Nauru',
  'Namibia',
  'Chad',
  'Tonga',
  'Argentina',
  'Christmas Island',
  'Niger',
  'Marshall Islands',
  'Costa Rica',
  'Ghana',
  'Austria',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Palestine',
  'Cuba',
  'Hungary',
  'Micronesia',
  'Belize',
  'Bahamas',
  'Aruba',
  'São Tomé and Príncipe',
  'Russia',
  'Luxembourg',
  'Faroe Islands',
  'Nicaragua',
  'Tunisia',
  'DR Congo',
  'Svalbard and Jan Mayen',
  'South Africa',
  'Sierra Leone',
  'Lesotho',
  'South Georgia',
  'Italy',
  'Djibouti',
  'Heard Island and McDonald Islands',
  'Sri Lanka',
  'Saint Lucia',
  'Samoa',
  'Cocos (Keeling) Islands',
  'Puerto Rico',
  'Gabon',
  'Turkmenistan',
  'Latvia',
  'Senegal',
  'Belgium',
  'Moldova',
  'Liechtenstein',
  'Malawi',
  'Lebanon',
  'Mongolia',
  'Norway',
  'British Virgin Islands',
  'Cameroon',
  'Thailand',
  'Nigeria',
  'Réunion',
  'Cape Verde',
  'Jersey',
  'Algeria',
  'Laos',
  'Caribbean Netherlands',
  'Azerbaijan',
  'Sint Maarten',
  'Morocco',
  'Åland Islands',
  'Bulgaria',
  'Burundi',
  'Uganda',
  'Kosovo',
  'Mozambique',
  'Georgia',
  'United Kingdom',
  'Wallis and Futuna',
  'Pitcairn Islands',
  'Romania',
  'Vietnam',
  'French Southern and Antarctic Lands',
  'Western Sahara',
  'Japan',
  'Egypt',
  'Liberia',
  'Lithuania',
  'Haiti',
  'United States Virgin Islands',
  'Papua New Guinea',
  'Hong Kong',
  'Kyrgyzstan',
  'Palau',
  'Madagascar',
  'Gambia',
  'Togo',
  'Tokelau',
  'Slovenia',
  'Singapore',
  'French Guiana',
  'United States',
  'Montserrat',
  'Malaysia',
  'Germany',
  'Antigua and Barbuda',
  'Saint Martin',
  'Somalia',
  'Macau',
  'Albania',
  'Mayotte',
  'Dominica',
  'Zambia',
  'Anguilla',
  'Cook Islands',
  'Martinique',
  'Guinea',
  'Comoros',
  'Niue',
  'Switzerland',
  'Norfolk Island',
  'Isle of Man',
  'Sudan',
  'Tajikistan',
  'Uruguay',
  'Cyprus',
  'Guinea-Bissau',
];
